version: '2.1'
services:

  ui-for-docker:
    restart: always
    image: uifd/ui-for-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9091:9000"

  watchtower:
    restart: always
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/Timm.Heuss/.docker/config.json:/config.json
    command: --interval 30


  logspout:
    image: gliderlabs/logspout:v3
    command: 'syslog://logstash:5000'
    links:
      - logstash
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'

  logstash:
    image: ludekvesely/logstash-json
    environment:
      - LOGSPOUT=ignore
      - DROP_NON_JSON=false
      - STDOUT=true
    links:
      - elasticsearch

  kibana:
    image: kibana
    environment:
      - LOGSPOUT=ignore
    links:
      - elasticsearch
    ports:
      - '5601:5601'

  elasticsearch:
    image: elasticsearch
    environment:
      - LOGSPOUT=ignore

